Add files via upload

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -1,6 +1,6 @@
 #!/bin/bash
 #====================================================
-#	@REYDASSH 
+#	@LOCKED_SSH 
 #====================================================
 cor1='\033[41;1;37m'
 cor2='\033[44;1;37m'
@@ -53,6 +53,18 @@ SCOLOR='\033[0m'
 				fun_conexao
 			}
 		done
+	}
+
+	slow_setup() {
+		[[ -e "/bin/slowdns" ]] && {
+			slowdns
+		} || {
+			cd $HOME
+			wget https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Slowdns/install -o /dev/null
+			chmod 777 install
+			./install
+		}
+
 	}
 
 	inst_sqd() {
@@ -465,7 +477,7 @@ SCOLOR='\033[0m'
         fun_v2rayins() {
 			clear
 	        v2rayinst(){
-	            source <(curl -sL https://raw.githubusercontent.com/Niltonjuniornzx/anubis/master/Modulos/v2ray)
+	            source <(curl -sL https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Modulos/v2ray)
                     sleep 6
 	        }
 	        if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
@@ -783,9 +795,9 @@ SCOLOR='\033[0m'
 				cd /etc/stunnel/
 				rm -rf stunnel.conf
 				rm -rf stunnel.pem
-				wget https://raw.githubusercontent.com/Niltonjuniornzx/anubis/master/Install/cert
-				wget https://raw.githubusercontent.com/Niltonjuniornzx/anubis/master/Install/key
-				wget https://raw.githubusercontent.com/Niltonjuniornzx/anubis/master/Install/stunnel
+				wget https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Install/cert
+				wget https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Install/key
+				wget https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Install/stunnel
 				mv cert cert.pem
 				mv key key.pem
 				mv stunnel stunnel.conf
@@ -1287,9 +1299,9 @@ SCOLOR='\033[0m'
 			# Adquirindo easy-rsa
 			echo ""
 			fun_dep() {
-				wget -O ~/EasyRSA-3.0.1.tgz "https://raw.githubusercontent.com/Niltonjuniornzx/anubis/master/Install/EasyRSA-3.0.1.tgz"
+				wget -O ~/EasyRSA-3.0.1.tgz "https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Install/EasyRSA-3.0.1.tgz"
 				[[ ! -e $HOME/EasyRSA-3.0.1.tgz ]] && {
-					wget -O ~/EasyRSA-3.0.1.tgz "http://sshplus.xyz/script/EasyRSA-3.0.1.tgz"
+					wget -O ~/EasyRSA-3.0.1.tgz "https://raw.githubusercontent.com/Lockednet/SCRIPT/main/Install/EasyRSA-3.0.1.tgz"
 				}
 				tar xzf ~/EasyRSA-3.0.1.tgz -C ~/
 				mv ~/EasyRSA-3.0.1/ /etc/openvpn/
@@ -2041,54 +2053,54 @@ exit 0' >$RCLOCAL
 system=$(cat /etc/issue.net)
 date=$(date '+%Y-%m-%d <> %H:%M:%S')
 echo -e "\033[1;37m $system                $date"
-echo -e "\033[01;36m║\033[1;31m\033[5;34;47m                      CONEXAO                      \033[1;33m \033[0m\033[01;36m║"
-echo -e "\033[0;36m║\033[0m"
-			echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mOPENSSH \033[1;32mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
+echo -e "\033[01;37m║\033[1;31m\033[46;1;37m                      CONEXÕES                    \033[1;33m \033[0m\033[01;37m║"
+echo -e "\033[0;37m║\033[0m"
+			echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mOPENSSH \033[1;36mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
 			[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
-				echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mCHISEL: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mCHISEL: \033[1;36mPORTA: \033[1;37m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts8="\033[1;32m◉ "
 			} || {
 				sts8="\033[1;31m○ "
 			}
-			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+			[[ "$(ps x | grep 'slowdns' | grep -v 'grep' | wc -l)" != '0' ]] && {
 				sts9="\033[1;32m◉ "
 			} || {
 				sts9="\033[1;31m○ "
 			}            
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
-				echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mSSLH: \033[1;36mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts7="\033[1;32m◉ "
 			} || {
 				sts7="\033[1;31m○ "
 			}
 
 			[[ "$(netstat -tlpn | grep 'openvpn' | wc -l)" != '0' ]] && {
-				echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mOPENVPN: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mOPENVPN: \033[1;36mPORTA: \033[1;37m$(netstat -nplt | grep 'openvpn' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts5="\033[1;32m◉ "
 			} || {
 				sts5="\033[1;31m○ "
 			}
 
 			[[ "$(netstat -tlpn | grep 'python' | wc -l)" != '0' ]] && {
-				echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mPROXY SOCKS \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mPROXY SOCKS \033[1;36mPORTA: \033[1;37m$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts4="\033[1;32m◉ "
 			} || {
 				sts4="\033[1;31m○ "
 			}
 			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
-				echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mSSL TUNNEL \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
+				echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mSSL TUNNEL \033[1;36mPORTA: \033[1;37m$(netstat -nplt | grep 'stunnel' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts3="\033[1;32m◉ "
 			} || {
 				sts3="\033[1;31m○ "
 			}
 			[[ "$(netstat -tlpn | grep 'dropbear' | wc -l)" != '0' ]] && {
-				echo -e "\033[01;3m║\033[1;32mSERVICO: \033[1;33mDROPBEAR \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
+				echo -e "\033[01;37m║\033[1;32mSERVICO: \033[1;33mDROPBEAR \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'dropbear' | awk -F ":" {'print $4'} | xargs)"
 				sts2="\033[1;32m◉ "
 			} || {
 				sts2="\033[1;31m○ "
 			}
 			[[ "$(netstat -tlpn | grep 'squid' | wc -l)" != '0' ]] && {
-				echo -e "\033[01;36m║\033[1;32mSERVICO: \033[1;33mSQUID \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
+				echo -e "\033[01;37m║\033[1;36mSERVICO: \033[1;37mSQUID \033[1;36mPORTA: \033[1;37m$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)"
 				sts1="\033[1;32m◉ "
 			} || {
 				sts1="\033[1;31m○ "
@@ -2103,84 +2115,82 @@ echo -e "\033[0;36m║\033[0m"
 			} || {
 				xv2ray="\033[1;31m○ "
 			}
-			echo -e "\033[0;36m╠━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━\033[0m"
-			echo -e "\033[01;36m║\033[0m"
-			echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;33mOPENSSH \033[01;31m $sts6\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;33mSQUID PROXY \033[01;31m $sts1\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;33mDROPBEAR \033[01;31m $sts2\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 04 •\033[1;34m]\033[1;37m ➩  \033[1;33mOPENVPN \033[01;31m $sts5\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 05 •\033[1;34m]\033[1;37m ➩  \033[1;33mPROXY SOCKS \033[01;31m $sts4\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 06 •\033[1;34m]\033[1;37m ➩  \033[1;33mSSL TUNNEL \033[01;31m $sts3\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 07 •\033[1;34m]\033[1;37m ➩  \033[1;33mSSLH MULTIPLEX \033[01;31m $sts7\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 08 •\033[1;34m]\033[1;37m ➩  \033[1;33mCHISEL \033[01;31m $sts8\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 09 •\033[1;34m]\033[1;37m ➩  \033[1;33mSLOWDNS \033[01;31m $sts9\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 10 •\033[1;34m]\033[1;37m ➩  \033[1;33mV2RAY \033[01;31m $xv2ray\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 11 •\033[1;34m]\033[1;37m ➩  \033[1;33mTROJAN-GO \033[01;31m $trojansts\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 12 •\033[1;34m]\033[1;37m ➩  \033[1;33mWEBSOCKET - Corretor \033[01;31m $sts3\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 13 •\033[1;34m]\033[1;37m ➩  \033[1;33mLIMPAR V2RAY \033[01;31m\033[0m"
-echo -e "\033[01;36m║\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;33mVOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
-echo -e "\033[01;36m║\033[0m"
-			echo -e "\033[0;36m╠━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+			echo -e "\033[0;37m╠━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━\033[0m"
+			echo -e "\033[01;37m║\033[0m"
+			echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 01 •\033[1;34m]\033[1;37m ➩  \033[1;37mOPENSSH \033[01;31m $sts6\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 02 •\033[1;34m]\033[1;37m ➩  \033[1;37mSQUID PROXY \033[01;31m $sts1\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 03 •\033[1;34m]\033[1;37m ➩  \033[1;37mDROPBEAR \033[01;31m $sts2\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 04 •\033[1;34m]\033[1;37m ➩  \033[1;37mOPENVPN \033[01;31m $sts5\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 05 •\033[1;34m]\033[1;37m ➩  \033[1;37mPROXY SOCKS \033[01;31m $sts4\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 06 •\033[1;34m]\033[1;37m ➩  \033[1;37mSSL TUNNEL \033[01;31m $sts3\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 07 •\033[1;34m]\033[1;37m ➩  \033[1;37mSSLH MULTIPLEX \033[01;31m $sts7\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 08 •\033[1;34m]\033[1;37m ➩  \033[1;37mCHISEL \033[01;31m $sts8\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 09 •\033[1;34m]\033[1;37m ➩  \033[1;37mSLOWDNS \033[01;31m $sts9\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 10 •\033[1;34m]\033[1;37m ➩  \033[1;37mTROJAN-GO \033[01;31m $trojansts\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 11 •\033[1;34m]\033[1;37m ➩  \033[1;37mWEBSOCKET - Corretor \033[01;31m $sts3\033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 12 •\033[1;34m]\033[1;37m ➩  \033[1;37mMENU APACHE  \033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 13 •\033[1;34m]\033[1;37m ➩  \033[1;37mV2RAY \033[1;31m ⚠️ SÓ PRA QUEM SABE!! ⚠️ \033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 14 •\033[1;34m]\033[1;37m ➩  \033[1;37mV2RAY  \033[0m"
+echo -e "\033[01;37m║\033[1;31m\033[1;34m[\033[1;37m 00 •\033[1;34m]\033[1;37m ➩  \033[1;31m VOLTAR  \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
+echo -e "\033[01;37m║\033[0m"
+			echo -e "\033[0;37m╠━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━═━\033[0m"
 			tput civis
-			echo -ne "\033[1;36m╰━━━━━━━━❪\033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : "; read x
-case "$x" in
+			echo -ne "\033[1;37m╰━━━━━━━━❪\033[1;36mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : ";
+			read x
+			tput cnorm
+			clear
+			case $x in
 			1 | 01)
-				fun_openssh
-				;;
+			fun_openssh
+			;;
 			2 | 02)
-				fun_squid
-				;;
+			fun_squid
+			;;
 			3 | 03)
-				fun_drop
-				;;
+			fun_drop
+			;;
 			4 | 04)
-				fun_openvpn
-				;;
+			fun_openvpn
+			;;
 			5 | 05)
-				fun_socks
-				;;
-			6 | 06)
-				inst_ssl
-				;;
+			fun_socks
+			;;
+			6 | 06) 
+			inst_ssl
+			;;
 			7 | 07)
-				fun_sslh
-				;;
+			fun_sslh
+			;;
 			8 | 08)
-				fun_chisel
-				;;
+			fun_chisel
+			;;
 			9 | 09)
-				slowdns
-				;;
+			slow_setup
+			;;
 			10 | 10)
-				v2raymanager
-				exit
-				;;
+			trojan-go
+			;;
 			11 | 11)
-				trojan-go
-				;;
+			websocket.sh
+			;;
 			12 | 12)
-				websocket.sh
-				;;
+			clear
+			apache2menu
+			;;
 			13 | 13)
-                                echo -e "\E[44;1;37m             LIMPAR V2RAY              \E[0m"
-                                echo -e "\033[1;31mESSA FUNÇÃO É PARA LIBERAR MEMÓRIA EM DISCO COMO MEMÓRIA RAM \033[1;33m \033[1;32\033[0m"
-echo -e "\033[1;31mTenha em mente que ao executá-lo, se você tivesse estatísticas de consumo, \033[1;33m \033[1;32\033[0m"
-echo -e "\033[1;31meles serão zerados, não há perda de configurações ou do usuário \033[1;33m \033[1;32\033[0m"
-				v2ray clean
-                                echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
-				;;
-                14 | 14)
-                clear
-				painelv2ray
-				;;
+			telks
+            ;;
+			14 | 14)
+			v2raymanager
+			;;
 			0 | 00)
-				clear
-				menu
-				;;
+			clear
+			menu
+			;;
 			*)
-				echo -e "\033[1;31mOpcao invalida !\033[0m"
-				sleep 2
-				;;
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			sleep 2
+			;;
 			esac
 		done
 	}
